### ISSUE TITLE
Registration site `config`

### ISSUE THREAD

**Issue by stripethree** [azbrscca/azbrscca.org#41]
The registration site has a similar configuration set up to the AZBR site. A few things would have to be done to make sure things don't collide. This assumes that a `dev` version of the registration site is desired. Thinking it through, here's what I think would need to be moved around or added to have it work:

One time tasks on the 1and1 server:
- [x] Move current `config/` contents to `config/azbrscca` and create `config/registration` for similar `Common.php.dev` and `Common.php.live` files. This will also result in a small code change to `configure.php` for the AZBR site
- [x]  Update the `post-receive` hook to reflect the new location of `Common.php.live` fort the AZBR site
- [x]  Set up a bare git repo in the `git` subdirectory for the registration site; this will allow the registration site to be deployed live with [similar instructions](https://github.com/azbrscca/azbrscca.org/wiki/Webmaster-Notes#deploying-to-the-live-site) just some different paths
- [x]  Create a `post-receive` hook for the registration site

In the AZBR codebase:
- No changes other than the aforementioned tweak to `configure.php`

In the Registration codebase:
- [x]  Update `configure.php`
- [x]  Set up a similar path for the database connection information, as that should not be in a repo anywhere
~3. Same for `reg-api/.htaccess`~ Not needed

I can take care of the setup of things for the registration site if that sounds good. That would include creating a repo in this org for the registration site.

**Comment by mreysser** [comment]
Yes, a dev version of the registration site is definitely desired.

If you make a repo for registration, I assume you will exclude the API keys?

Manfred Reysser

**Comment by stripethree** [comment]
Yes, there are few files to exclude which can migrate to the same pattern as `Common.php`.
It should not be too much work to get going.

**Comment by mreysser** [comment]
Sounds good, go ahead. Thanks!!!

**Comment by stripethree** [comment]
👍 Once #42 lands I'll get the last two things on the list here checked off and we're good to go.
